### ISSUE TITLE
Create Modified library Schematic 

### ISSUE THREAD

**Issue by paullryan** [nrwl/nx-incremental-large-repo#2]
Needs a library schematic that automatically adds the paths of a new library to all projects by default.

@vsavkin I'm just adding these as placeholders of items still needing attention before this process is ready for a production team. Please feel free to modify, move, discuss, delete as appropriate

**Comment by juristr** [comment]
Just merged some changes which doesn't need those path mappings any more since they're done automatically at run-time.
