### ISSUE TITLE
why do we have duplicate tsconfig path mapping for app0/tsconfig.app.json and root/tsconfig.json

### ISSUE THREAD

**Issue by VeeteshJain** [nrwl/nx-incremental-large-repo#4]
@vsavkin why do we need to have 2 different path mapping for @largerepo/app0/lib0/lib0 
one at [apps/app0/tsconfig.app.json](https://github.com/nrwl/nx-incremental-large-repo/blob/master/apps/app0/tsconfig.app.json#L7)  from dist 
and another one at project root [tsconfig.json](https://github.com/nrwl/nx-incremental-large-repo/blob/master/tsconfig.json#L19) from libs?

questions 
1. do we need to maintain these 2 lists separately?
2. is there is some nx comonad to add or validate such links?

**Comment by juristr** [comment]
I just merged some changes into master that should fix the above mentioned issue. Note this is still experimental and a production ready version will be shipped with v11.
